# Couldn't find class for name VERSION
# Couldn't find class for name LoggerBuffer
# Couldn't find class for name Methods
# Code Generated by ZenTest v. 3.10.0
#                 classname: asrt / meth =  ratio%
#                   Methods:    0 /    1 =   0.00%
#     Commander::MockStatus:    0 /    5 =   0.00%
#              LoggerBuffer:    0 /    1 =   0.00%

require 'test/unit' unless defined? $ZENTEST and $ZENTEST

class TestCommander < Test::Unit::TestCase
  def setup
    logger = Logger.new( STDOUT )
    @c = Commander.new( logger )
  end
  
  def test_commands
    assert( true, @c.respond_to?(:commands) )
  end

  def test_commands_equals
    assert_equal( Array, @c.commands.class )
  end

  def test_errors_eh
    assert( true, @c.respond_to?(:errors?) )
  end

  def test_exit_status
    assert( true, @c.respond_to?(:exit_status) )
  end

  def test_exit_status_equals
    assert_equal( 0, @c.exit_status )
  end

  def test_log
    assert( true, @c.respond_to?(:log) )
  end

  def test_log_equals
    assert( Logger, @c.log.class )
  end

  def test_run
    assert( true, @c.respond_to?(:run) )
  end

  def test_run_commands
    assert( true, @c.respond_to?(:run_commands) )
  end

  class TestMockStatus < Test::Unit::TestCase
    def test_exitstatus
      assert_equal( 1, Commander::MockStatus.new().exitstatus() )
    end
  end

end
# Number of errors detected: 12